# Site settings
title: Filip Tomasz Wieland
email: filiplamparski@gmail.com
description: "Software developer and web enthusiast. Let me help you make your next great app."
baseurl: ""
url: "http://www.filipwieland.com"
github_username:  FLamparski

# Build settings
markdown: kramdown
permalink: pretty
