# Site settings
title: Filip Tomasz Wieland
email: hello@filipwieland.com
description: "Observations on software, science, and politics."
baseurl: ""
url: "http://www.filipwieland.com"
github_username:  FLamparski

# Build settings
markdown: kramdown
permalink: pretty
